/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NCNotificationWindowDelegate-Protocol.h"

@protocol NCAlertDelegate <NCNotificationWindowDelegate>
- (void)alert:(id)arg1 snoozedWithTimeInterval:(double)arg2;
- (void)alertClose:(id)arg1;
- (void)alertPerformActionAndDismiss:(id)arg1;
- (void)alertViewNotification:(id)arg1;
@end

