/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol NCAppInfoDelegate <NSObject>
- (void)app:(id)arg1 foundAtLocation:(id)arg2;
- (void)appUnreadNotificationsChanged:(id)arg1;
- (void)appNotFound:(id)arg1;
@end

