/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NCAppInfoDelegate-Protocol.h"

@class NSArray, NSDictionary, NSImage, NSMutableArray, NSMutableDictionary, NSObject, NSString, NSURL;

@interface NCAppInfo : NSObject
{
    NSString *_name;
    NSImage *_image;
    NSString *_bundleIdentifier;
    BOOL _found;
    NSArray *_notifications;
    NSMutableArray *_unseenNotifications;
    unsigned long long _notificationsToShow;
    BOOL _showInNotificationCenter;
    BOOL _playSounds;
    BOOL _badgeIcons;
    BOOL _warnedAboutInvalidIdentity;
    unsigned long long _alertStyle;
    NSURL *_lastKnownURL;
    NSObject<OS_dispatch_source> *_delivered_timer;
    id _delivered_block;
    double _sound_last_play_time;
    double _lastestNotificationTime;
    NSMutableDictionary *_soundDictionary;
    id <NCAppInfoDelegate> delegate;
    id <NCAppInfoDelegate> _delegate;
    BOOL _needsToFetchData;
}

@property BOOL needsToFetchData; // @synthesize needsToFetchData=_needsToFetchData;
@property(readonly) BOOL found; // @synthesize found=_found;
@property double lastestNotificationTime; // @synthesize lastestNotificationTime=_lastestNotificationTime;
@property unsigned long long alertStyle; // @synthesize alertStyle=_alertStyle;
@property BOOL playSounds; // @synthesize playSounds=_playSounds;
@property BOOL badgeIcons; // @synthesize badgeIcons=_badgeIcons;
@property BOOL showInNotificationCenter; // @synthesize showInNotificationCenter=_showInNotificationCenter;
@property unsigned long long notificationsToShow; // @synthesize notificationsToShow=_notificationsToShow;
@property(retain, nonatomic) NSArray *notifications; // @synthesize notifications=_notifications;
@property(readonly) NSImage *image; // @synthesize image=_image;
@property(readonly) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(readonly) NSString *name; // @synthesize name=_name;
@property id <NCAppInfoDelegate> delegate; // @synthesize delegate=_delegate;
- (void)clearUnreadNotificationMatching:(id)arg1;
- (void)clearUnreadNotifications;
- (void)setDeliveredActionBlock:(id)arg1;
- (void)playSound:(id)arg1;
- (void)_playSoundWithBlock:(id)arg1;
- (void)lookupInfoInBackgroundOnQueue:(id)arg1;
@property(copy) NSDictionary *preferenceDictionary;
@property(readonly) BOOL clearable;
@property(readonly) NSString *lastKnownPath;
@property(readonly) BOOL hasUnreadNotifications;
- (void)dealloc;
- (id)initWithBundleIdentifier:(id)arg1 lastKnownPath:(id)arg2 loadInfoOnQueue:(id)arg3;

@end

