/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NCNotificationWindowDelegate-Protocol.h"

@protocol NCBannerDelegate <NCNotificationWindowDelegate>
- (void)bannerAnimatedOut:(id)arg1;
- (void)bannerMoreClicked:(id)arg1;
- (void)bannerCloseClicked:(id)arg1;
- (void)bannerClicked:(id)arg1;
@end

