/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "QLPreviewItem-Protocol.h"

@class NCAppInfo, NCWidget, NSString, NSURL, NSUserNotification;

@interface NCModel : NSObject <QLPreviewItem>
{
    NCAppInfo *_app;
    NSUserNotification *_note;
    BOOL _drawsDividerLine;
    double _cachedRowHeight;
    unsigned long long _notesRepresented;
    NCWidget *_widget;
}

+ (id)modelWithApp:(id)arg1 note:(id)arg2;
@property(retain) NCWidget *widget; // @synthesize widget=_widget;
@property unsigned long long notesRepresented; // @synthesize notesRepresented=_notesRepresented;
@property double cachedRowHeight; // @synthesize cachedRowHeight=_cachedRowHeight;
@property BOOL drawsDividerLine; // @synthesize drawsDividerLine=_drawsDividerLine;
@property(retain) NSUserNotification *note; // @synthesize note=_note;
@property(retain) NCAppInfo *app; // @synthesize app=_app;
@property(readonly) NSString *previewItemTitle;
@property(readonly) NSURL *previewItemURL;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;

// Remaining properties
@property(readonly) id previewItemDisplayState;

@end

