/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol NCNotificationWindowDelegate <NSObject>
- (void)notificationWindow:(id)arg1 velocity:(double)arg2 draggedCompleted:(BOOL)arg3;
- (void)notificationWindow:(id)arg1 dragged:(id)arg2;
- (BOOL)notificationWindow:(id)arg1 dragStarted:(id)arg2;
- (void)notificationWindowSwipeEnded:(id)arg1 cancelled:(BOOL)arg2;
- (void)notificationWindowSwipeProgressed:(id)arg1 progress:(double)arg2;
- (BOOL)notificationWindowSwipeStarted:(id)arg1 rightToLeft:(BOOL)arg2 withEvent:(id)arg3;
- (BOOL)notificationWindowCanSwipe:(id)arg1 left:(BOOL)arg2;
@end

