/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NCRoundedWindowContentDelegate-Protocol.h"
#import "NCNotificationWindowDelegate-Protocol.h"

@class NCAppInfo, NCBannerViewController, NCModel, NCRoundedWindowContentView, NSLayoutConstraint, NSMutableSet, NSString, NSUserNotification, NSView;

@interface NCNotificationWindow : NSObject <NCRoundedWindowContentDelegate>
{
    NCBannerViewController *_contentViewController;
    NCRoundedWindowContentView *_view;
    NSView *_containerView;
    NSMutableSet *_constraints;
    NSLayoutConstraint *_horizontalLayoutConstraint;
    BOOL applicationUpdated;
    BOOL _closing;
    BOOL _needsLayout;
    char *_swipeAnimationCanceled;
    BOOL _trackingSwipes;
    BOOL _addedObsever;
    BOOL _movedAside;
    id <NCNotificationWindowDelegate> _delegate;
    BOOL _hiddenDueToOverflow;
}

+ (unsigned long long)minNotificationHeight;
+ (unsigned long long)maxNotificationHeight;
+ (unsigned long long)notificationWidth;
@property(readonly) BOOL needsLayout; // @synthesize needsLayout=_needsLayout;
@property BOOL hiddenDueToOverflow; // @synthesize hiddenDueToOverflow=_hiddenDueToOverflow;
@property(readonly) NSMutableSet *constraints; // @synthesize constraints=_constraints;
@property id <NCNotificationWindowDelegate> delegate; // @synthesize delegate=_delegate;
@property BOOL movedAside; // @synthesize movedAside=_movedAside;
@property(retain) NSLayoutConstraint *horizontalLayoutConstraint; // @synthesize horizontalLayoutConstraint=_horizontalLayoutConstraint;
@property(readonly) NCRoundedWindowContentView *view; // @synthesize view=_view;
@property(readonly) NCBannerViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
- (void)contentView:(id)arg1 velocity:(double)arg2 draggedCompleted:(BOOL)arg3;
- (void)contentView:(id)arg1 dragged:(id)arg2;
- (BOOL)contentView:(id)arg1 dragStarted:(id)arg2;
- (BOOL)contentView:(id)arg1 scrolled:(id)arg2;
- (void)performDropInAnimationWithDuration:(double)arg1 completion:(id)arg2;
- (void)cancelTalkingAlert;
- (void)registerTalkingAlertIfNecessary;
- (void)pulseIcon;
- (void)windowAnimateOutComplete;
- (void)windowAnimateOutStart;
- (void)windowAnimateInComplete;
- (void)dumpLayerTree;
- (void)removeFromView;
- (void)modelDidUpdate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layout;
- (void)_updateViewFromModel;
@property(retain, nonatomic) NCModel *model;
@property(readonly) NCAppInfo *application;
@property(readonly) NSUserNotification *notification;
@property(readonly) BOOL onScreen;
@property(readonly) NSString *accessibilitySubRole;
- (void)dealloc;
- (id)initWithModel:(id)arg1;

@end

