/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NCAlertDelegate-Protocol.h"
#import "NCBannerDelegate-Protocol.h"
#import "NCWindowLayoutDelegate-Protocol.h"

@class NCAlert, NCBanner, NCModel, NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject, NSTrackingArea, NSView, NSWindow, _NCAlertsAndBannersWindow;

@interface NCWindowLayoutController : NSObject <NCBannerDelegate, NCAlertDelegate>
{
    struct CGRect _visibleRect;
    struct CGRect _screenRect;
    _NCAlertsAndBannersWindow *_window;
    NSView *_contentView;
    BOOL _needsLayout;
    NSMutableArray *_verticalConstraints;
    long long _windowRaisedCount;
    NSTrackingArea *_windowTrackingArea;
    NSMutableArray *_alerts;
    NSMutableSet *_windowsToRemoveOnNextLayout;
    NSMutableDictionary *_alertsPerApplication;
    NSMutableArray *_overflowAlerts;
    NCAlert *_keyAlert;
    BOOL _restoringAlerts;
    double _bannerTime;
    NSMutableArray *_bannerQueue;
    double _currentBannerTime;
    NCBanner *_currentBanner;
    NCModel *_pendingBanner;
    NSObject<OS_dispatch_source> *_banner_timer;
    NSObject<OS_dispatch_source> *_banner_performance_timer;
    struct CGPoint _lastMousePosition;
    unsigned long long _ignoredBanners;
    double _dropDownAnimationDuration;
    double _leftColumnConstraintConstant;
    double _rightColumnConstraintConstant;
    NSObject<OS_dispatch_source> *_alert_move_timer;
    double _alertMoveTime;
    BOOL _windowBeingSwiped;
    BOOL _alertsDisabled;
    BOOL _allowDragToLeft;
    id <NCWindowLayoutDelegate> _delegate;
    BOOL _centerOpen;
}

@property(nonatomic) BOOL alertsDisabled; // @synthesize alertsDisabled=_alertsDisabled;
@property(nonatomic) BOOL centerOpen; // @synthesize centerOpen=_centerOpen;
@property(readonly) NSWindow *window; // @synthesize window=_window;
@property id <NCWindowLayoutDelegate> delegate; // @synthesize delegate=_delegate;
- (void)alert:(id)arg1 snoozedWithTimeInterval:(double)arg2;
- (void)alertClose:(id)arg1;
- (void)alertPerformActionAndDismiss:(id)arg1;
- (void)alertViewNotification:(id)arg1;
- (void)bannerAnimatedOut:(id)arg1;
- (void)bannerMoreClicked:(id)arg1;
- (void)bannerCloseClicked:(id)arg1;
- (void)bannerClicked:(id)arg1;
- (void)notificationWindow:(id)arg1 velocity:(double)arg2 draggedCompleted:(BOOL)arg3;
- (void)notificationWindow:(id)arg1 dragged:(id)arg2;
- (BOOL)notificationWindow:(id)arg1 dragStarted:(id)arg2;
- (void)notificationWindowSwipeEnded:(id)arg1 cancelled:(BOOL)arg2;
- (void)notificationWindowSwipeProgressed:(id)arg1 progress:(double)arg2;
- (BOOL)notificationWindowSwipeStarted:(id)arg1 rightToLeft:(BOOL)arg2 withEvent:(id)arg3;
- (BOOL)notificationWindowCanSwipe:(id)arg1 left:(BOOL)arg2;
- (void)_lockAnimatingOutViewYPosition:(id)arg1;
- (void)animateOutSlide:(id)arg1 duration:(double)arg2;
- (void)animateOutFade:(id)arg1 duration:(double)arg2;
- (void)animateInFade:(id)arg1 duration:(double)arg2;
- (void)animateInDrop:(id)arg1 duration:(double)arg2;
- (void)_animateDuration:(double)arg1 identifier:(id)arg2 withAnimation:(id)arg3 completion:(void)arg4;
- (void)_addWindow:(id)arg1 startsHidden:(BOOL)arg2;
- (void)startWatchingMouseToMoveAlertsBack;
- (void)mouseExited:(id)arg1;
- (void)_checkMousePosition;
- (void)mouseEntered:(id)arg1;
- (void)createTrackingArea;
- (void)removeTrackingArea;
- (void)_orderWindowOnIfNecessary;
- (void)_orderWindowOutIfNecessary;
- (void)_fixupWindowOrder:(id)arg1;
- (void)_verticalLayout;
- (struct CGRect)_windowFrame;
- (void)_animateAlertOff:(id)arg1 poof:(BOOL)arg2 slide:(BOOL)arg3;
- (void)_removeAlert:(id)arg1;
- (void)_addAlert:(id)arg1;
- (id)_alertMatchingAlert:(id)arg1 forApplication:(id)arg2;
- (void)_presentAlert:(id)arg1;
- (void)_dismissAndReleaseBanner:(id)arg1;
- (void)_actuallyDisplayBanner:(id)arg1 inPlace:(BOOL)arg2;
- (void)_presentBanner:(id)arg1 withUnpresentedCount:(unsigned long long)arg2;
- (void)debugDump:(id)arg1;
- (BOOL)switchKeyNotification:(BOOL)arg1;
- (BOOL)canSwitchKeyNotifications;
- (void)layoutWindowForScreenRect:(struct CGRect)arg1 visibleRect:(struct CGRect)arg2;
- (void)needsLayout;
- (void)layout;
- (void)removeAllDisplayedNotificationsForApplication:(id)arg1;
- (void)removeDisplayedNotification:(id)arg1 forApplication:(id)arg2;
- (void)restoreDisplayedNotifications:(id)arg1 forApplication:(id)arg2;
- (void)displayNotification:(id)arg1 forApplication:(id)arg2 withUnpresentedCount:(unsigned long long)arg3;
- (void)dealloc;
- (id)initWithScreenFrame:(struct CGRect)arg1 andVisibleFrame:(struct CGRect)arg2 spaces:(struct __CFArray *)arg3;

@end

